[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
scylla = "1.4.1"
rocket = "0.5.1"
rust_socketio = "0.6.0"
serde_json = "1.0.59"
dotenvy = "0.15"
diesel = { version = "2.3.5", features = ["postgres"] }