services:
  main-nosql:
    container_name: python-main-nosql
    image: scylladb/scylla
    ports:
      - "9042:9042"
      - "7000:7000"
      - "7001:7001"
      - "10000:10000"
    volumes:
      - scylla-data:/var/lib/scylla
    networks:
      - python-backend-network
    env_file:
      - .env
  # nosql-monitor:
  #   container_name: python-main-nosql-monitor
  #   image: scylladb/scylla-manager
  #   ports:
  #     - "10001:10001"
  #   volumes:
  #     - scylla-manager:/var/lib/scylla-manager
  #   networks:
  #     - python-backend-network
  #   env_file:
  #     - .env
  main-sql:
    container_name: python-main-sql
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5450:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - python-backend-network
networks:
  python-backend-network:
    driver: bridge

volumes:
  scylla-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/scylla-data
      o: bind
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/pgdata
      o: bind
  scylla-manager:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/scylla-manager
      o: bind